### PR TITLE
Remove global variables

### PR DESCRIPTION
**Pull request by nils-ohlmeier**
This is a big refactoring to removed all the global variables to fix issue #60

### CODE REVIEW

**Comment by jsmolic** [comment]
Hi @nils-ohlmeier could you please issue a new release, I'm trying to patch the Gentoo gcc-10 bug (https://bugs.gentoo.org/706350) but there are lots of changes here, it would be simpler to package a new release.

**Comment by nils-ohlmeier** [comment]
@jsmolic I'm still working on making the refactored code a little better. And I would like add more test coverage. But maybe it is reasonable to delay that into another later release.

**Comment by nils-ohlmeier** [comment]
@jsmolic just published release 0.9.8 https://github.com/nils-ohlmeier/sipsak/releases/tag/0.9.8

**Comment by jsmolic** [comment]
@nils-ohlmeier Great, thank you :)

**Pull request merged**
